//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden üretildiğinde kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------


namespace deneme9
{
    public partial class Araç_Muayne_Takibi
    {
    }
}
